# Generated by Django 2.0.5 on 2018-06-20 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=150, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='手機格式不符合', regex='/^09\\d{2}-?\\d{3}-?\\d{3}$/')], verbose_name='手機'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
    ]
