# Generated by Django 2.0.5 on 2018-06-20 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180620_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='手機格式不符合', regex='^09\\d{2}-?\\d{3}-?\\d{3}$')], verbose_name='手機'),
        ),
    ]
