version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: gunicorn -c gunicorn.conf.py core.wsgi
    volumes:
      - static_volume:/usr/src/app/collect_static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ../.env
    depends_on:
      - db
  db:
    image: postgres:10.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/collect_static
      - media_volume:/usr/src/app/media
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: