# Generated by Django 2.0.5 on 2018-06-03 07:41

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180525_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=books.models.book_directory_path),
        ),
    ]
