# Generated by Django 2.0.5 on 2018-06-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship',
            field=models.BooleanField(default=False),
        ),
    ]
