# Generated by Django 2.0.5 on 2018-06-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180603_1541'),
        ('orders', '0002_order_ship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'book')},
        ),
    ]
